FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive \
RUST_VERSION=1.86.0

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl build-essential git ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain ${RUST_VERSION}

ENV PATH=/root/.cargo/bin:$PATH

WORKDIR /src
